### ISSUE TITLE
git-radar

### ISSUE THREAD

**Issue by oppianmatt** [justinmayer/tackle#13]
Whilst vcprompt is nice, git-radar displays more useful info.

https://github.com/michaeldfallen/git-radar

**Comment by justinmayer** [comment]
Hi Matt. Here are the reasons why I chose `vcprompt`:

1. It is written in C, so it's extremely fast.
2. It supports five version control systems (instead of just Git)
3. It provides the information I need.
4. Did I mention it's fast?

That said, the primary purpose of `vcprompt` is quite narrow and focused: _determine whether the current working directory is under version control_. Once that determination is made, there's no need to rely on the information that `vcprompt` provides, and then another tool (such as Git Radar) can be utilized to provide the information desired for the prompt.

In fact, that's precisely how the Mercurial-specific prompt is implemented. First, `vcprompt` determines whether the current working directory is under version control, and if so, whether it's Git or Mercurial. Then, if it's Mercurial, [`hg-prompt` is invoked](https://github.com/justinmayer/tackle/blob/master/themes/entropy/fish_prompt.fish#L56) to provide the desired information. This same two-step process, which is again done for performance reasons, could be implemented for Git as well.

So while the current version of the Entropy theme relies on `vcprompt` for Git working copy info, there's no reason Git Radar couldn't be used to provide additional information for the prompt. If you wanted to submit a pull request to that effect, you might consider adding a setting (perhaps `tacklebox_theme_git_prompt`) to allow folks to choose between the current default behavior and the alternative information that Git Radar would provide.

Make sense?
